version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-init-job:
    build:
      context: ./db-init-job
    container_name: db-init-job
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: url_shortener
      PGPASSWORD: postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"

  shorten-url-service:
    build:
      context: ./shorten-url-service
      dockerfile: docker/Dockerfile
    container_name: shorten-url-service
    depends_on:
      - postgres
      - db-init-job
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      INSTANCE_ID: shorten-143
      REGION: isrl-private-docker.desktop
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
      - "5005:5005"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.50"

volumes:
  postgres_data:
  redis_data: